Repository KKUMTEUL/KKUMTEUL-backend, pull requests merged in 2024-10, with the labels that each got.

#16 Feat: MBTI 및 성향 조사 기능 구현
  src/main/java/com/kkumteul/domain/childprofile/entity/ChildProfile.java
  src/main/java/com/kkumteul/domain/childprofile/entity/CumulativeMBTIScore.java
  src/main/java/com/kkumteul/domain/childprofile/entity/GenreScore.java
  src/main/java/com/kkumteul/domain/childprofile/entity/TopicScore.java
  src/main/java/com/kkumteul/domain/childprofile/repository/CumulativeMBTIScoreRepository.java
  src/main/java/com/kkumteul/domain/childprofile/repository/GenreScoreRepository.java
  src/main/java/com/kkumteul/domain/childprofile/repository/TopicScoreRepository.java
  src/main/java/com/kkumteul/domain/childprofile/service/ChildProfileService.java
  src/main/java/com/kkumteul/domain/code/controller/CommonCodeController.java
  src/main/java/com/kkumteul/domain/code/dto/CodeDto.java
  src/main/java/com/kkumteul/domain/code/repository/CommonCodeRepository.java
  src/main/java/com/kkumteul/domain/code/service/CommonCodeService.java
  src/main/java/com/kkumteul/domain/history/entity/ChildPersonalityHistory.java
  src/main/java/com/kkumteul/domain/history/entity/FavoriteGenre.java
  src/main/java/com/kkumteul/domain/history/entity/FavoriteTopic.java
  src/main/java/com/kkumteul/domain/history/entity/MBTIScore.java
  src/main/java/com/kkumteul/domain/history/repository/ChildPersonalityHistoryRepository.java
  src/main/java/com/kkumteul/domain/history/repository/FavoriteGenreRepository.java
  src/main/java/com/kkumteul/domain/history/repository/FavoriteTopicRepository.java
  src/main/java/com/kkumteul/domain/history/repository/MBTIScoreRepository.java
  src/main/java/com/kkumteul/domain/history/service/ChildPersonalityHistoryService.java
  src/main/java/com/kkumteul/domain/mbti/dto/MBTIPercentageDto.java
  src/main/java/com/kkumteul/domain/mbti/entity/MBTIName.java
  src/main/java/com/kkumteul/domain/mbti/entity/MBTIScore.java
  src/main/java/com/kkumteul/domain/mbti/repository/MBTIRepository.java
  src/main/java/com/kkumteul/domain/mbti/service/MBTIService.java
  src/main/java/com/kkumteul/domain/personality/repository/GenreRepository.java
  src/main/java/com/kkumteul/domain/personality/repository/TopicRepository.java
  src/main/java/com/kkumteul/domain/survey/controller/SurveyController.java
  src/main/java/com/kkumteul/domain/survey/dto/FavoriteDto.java
  src/main/java/com/kkumteul/domain/survey/dto/MBTISurveyAnswerDto.java
  src/main/java/com/kkumteul/domain/survey/dto/MbtiDto.java
  src/main/java/com/kkumteul/domain/survey/dto/SurveyResultDto.java
  src/main/java/com/kkumteul/domain/survey/dto/SurveyResultRequestDto.java
  src/main/java/com/kkumteul/domain/survey/service/pattern/SurveyFacade.java
  src/main/java/com/kkumteul/domain/survey/service/pattern/SurveyFacadeImpl.java
  src/main/java/com/kkumteul/exception/ChildProfileNotFoundException.java
  src/main/java/com/kkumteul/exception/EntityNotFoundException.java
  src/main/java/com/kkumteul/exception/HistoryNotFoundException.java
  src/main/java/com/kkumteul/exception/InvalidMBTINameException.java
  src/main/java/com/kkumteul/exception/handler/GlobalExceptionHandler.java
  src/test/java/com/kkumteul/domain/code/controller/CommonCodeControllerTest.java
  src/test/java/com/kkumteul/domain/code/repository/CommonCodeRepositoryTest.java
  src/test/java/com/kkumteul/domain/code/service/CommonCodeServiceTest.java
Labels: ✨ Feat

#18 Feat: 자녀 정보 상세보기 API 구현
  src/main/java/com/kkumteul/domain/book/dto/BookLikeDto.java
  src/main/java/com/kkumteul/domain/book/repository/BookLikeRepository.java
  src/main/java/com/kkumteul/domain/childprofile/controller/ChildProfileController.java
  src/main/java/com/kkumteul/domain/childprofile/dto/ChildProfileResponseDto.java
  src/main/java/com/kkumteul/domain/childprofile/repository/ChildProfileRepository.java
  src/main/java/com/kkumteul/domain/childprofile/service/ChildProfileService.java
  src/main/java/com/kkumteul/domain/history/dto/ChildPersonalityHistoryDto.java
  src/main/java/com/kkumteul/domain/history/repository/ChildPersonalityHistoryRepository.java
  src/test/java/com/kkumteul/domain/childprofile/controller/ChildProfileControllerTest.java
Labels: ✨ Feat

#15 Feat: 회원 정보 관리 API 구현
  src/main/java/com/kkumteul/domain/childprofile/dto/ChildProfileDetailDto.java
  src/main/java/com/kkumteul/domain/childprofile/entity/ChildProfile.java
  src/main/java/com/kkumteul/domain/history/entity/ChildPersonalityHistory.java
  src/main/java/com/kkumteul/domain/user/controller/UserController.java
  src/main/java/com/kkumteul/domain/user/dto/UserResponseDto.java
  src/main/java/com/kkumteul/domain/user/dto/UserUpdateRequestDto.java
  src/main/java/com/kkumteul/domain/user/entity/User.java
  src/main/java/com/kkumteul/domain/user/repository/UserRepository.java
  src/main/java/com/kkumteul/domain/user/service/UserService.java
  src/main/java/com/kkumteul/exception/GlobalExceptionHandler.java
  src/main/java/com/kkumteul/exception/UserNotFoundException.java
  src/test/java/com/kkumteul/domain/user/controller/UserControllerTest.java
  src/test/java/com/kkumteul/domain/user/repository/UserRepositoryTest.java
  src/test/java/com/kkumteul/domain/user/service/UserServiceTest.java
Labels: ✨ Feat, 🎶 wontfix

#24 Test: MBTI 설문 관련 테스트 코드 작성
  src/main/java/com/kkumteul/domain/survey/service/pattern/SurveyFacadeImpl.java
  src/test/java/com/kkumteul/domain/childprofile/controller/ChildProfileControllerTest.java
  src/test/java/com/kkumteul/domain/childprofile/repository/CumulativeMBTIScoreRepositoryTest.java
  src/test/java/com/kkumteul/domain/childprofile/repository/GenreScoreRepositoryTest.java
  src/test/java/com/kkumteul/domain/childprofile/repository/TopicScoreRepositoryTest.java
  src/test/java/com/kkumteul/domain/childprofile/service/ChildProfileServiceTest.java
  src/test/java/com/kkumteul/domain/history/repository/ChildPersonalityHistoryRepositoryTest.java
  src/test/java/com/kkumteul/domain/history/service/ChildPersonalityHistoryServiceTest.java
  src/test/java/com/kkumteul/domain/mbti/repository/MBTIRepositoryTest.java
  src/test/java/com/kkumteul/domain/mbti/service/MBTIServiceTest.java
  src/test/java/com/kkumteul/domain/survey/controller/SurveyControllerTest.java
  src/test/java/com/kkumteul/domain/survey/service/pattern/SurveyFacadeTest.java
Labels: ✨ Feat

#14 Feat: 도서 페이지 API 구현
  src/main/java/com/kkumteul/domain/book/controller/BookController.java
  src/main/java/com/kkumteul/domain/book/dto/GetBookDetailResponseDto.java
  src/main/java/com/kkumteul/domain/book/dto/GetBookListResponseDto.java
  src/main/java/com/kkumteul/domain/book/entity/Book.java
  src/main/java/com/kkumteul/domain/book/exception/BookNotFoundException.java
  src/main/java/com/kkumteul/domain/book/repository/BookRepository.java
  src/main/java/com/kkumteul/domain/book/repository/BookTopicRepository.java
  src/main/java/com/kkumteul/domain/book/service/BookService.java
  src/main/java/com/kkumteul/domain/book/service/impl/BookServiceImpl.java
  src/main/java/com/kkumteul/domain/personality/entity/Topic.java
  src/test/java/com/kkumteul/book/controller/BookControllerTest.java
  src/test/java/com/kkumteul/book/repository/BookRepositoryTest.java
  src/test/resources/images/book_1.jpg
  src/test/resources/images/topic_1.jpg
Labels: ✨ Feat, 🎶 wontfix

#33 Feat: 히스토리 논리/물리 삭제 구현
  build.gradle
  src/main/java/com/kkumteul/config/DeleteHistoryBatchConfig.java
  src/main/java/com/kkumteul/config/scheduler/DeleteHistoryScheduler.java
  src/main/java/com/kkumteul/domain/history/controller/ChildPersonalityHistoryController.java
  src/main/java/com/kkumteul/domain/history/entity/ChildPersonalityHistory.java
  src/main/java/com/kkumteul/domain/history/repository/ChildPersonalityHistoryRepository.java
  src/main/java/com/kkumteul/domain/history/service/ChildPersonalityHistoryService.java
  src/test/java/com/kkumteul/batch/DeleteHistoryBatchConfigTest.java
  src/test/java/com/kkumteul/config/DeleteHistoryBatchTestConfig.java
Labels: ✨ Feat

#31 Refactor: MBTI 설문 관련 리팩토링
  src/main/java/com/kkumteul/domain/childprofile/entity/CumulativeMBTIScore.java
  src/main/java/com/kkumteul/domain/childprofile/service/ChildProfileService.java
  src/main/java/com/kkumteul/domain/childprofile/service/PersonalityScoreService.java
  src/main/java/com/kkumteul/domain/history/service/ChildPersonalityHistoryService.java
  src/main/java/com/kkumteul/domain/mbti/service/MBTIService.java
  src/main/java/com/kkumteul/domain/survey/controller/SurveyController.java
  src/main/java/com/kkumteul/domain/survey/service/pattern/SurveyFacade.java
  src/main/java/com/kkumteul/domain/survey/service/pattern/SurveyFacadeImpl.java
Labels: 🚀 Refactor

#44 Refactor: MBTI 설문 점수 부여 방식 수정 및 프로필 변경 수정
  src/main/java/com/kkumteul/domain/childprofile/service/PersonalityScoreService.java
  src/main/java/com/kkumteul/domain/history/service/ChildPersonalityHistoryService.java
  src/main/java/com/kkumteul/domain/mbti/service/MBTIService.java
  src/main/java/com/kkumteul/domain/survey/service/pattern/SurveyFacadeImpl.java
Labels: 🚀 Refactor, 🛠️ Fix

#42 Fix: MBTI 설문 리팩토링에 따른 테스트 코드 수정
  src/test/java/com/kkumteul/domain/childprofile/service/ChildProfileServiceTest.java
  src/test/java/com/kkumteul/domain/childprofile/service/PersonalityScoreServiceTest.java
  src/test/java/com/kkumteul/domain/survey/controller/SurveyControllerTest.java
  src/test/java/com/kkumteul/domain/survey/service/pattern/SurveyFacadeTest.java
Labels: 🛠️ Fix

#39 Feat: 도서 키워드 검색 시 API 구현
  src/main/java/com/kkumteul/domain/book/controller/BookController.java
  src/main/java/com/kkumteul/domain/book/dto/GetBookDetailResponseDto.java
  src/main/java/com/kkumteul/domain/book/dto/GetBookListResponseDto.java
  src/main/java/com/kkumteul/domain/book/dto/PostBookLikeRequestDto.java
  src/main/java/com/kkumteul/domain/book/entity/Book.java
  src/main/java/com/kkumteul/domain/book/entity/BookLike.java
  src/main/java/com/kkumteul/domain/book/exception/BookNotFoundException.java
  src/main/java/com/kkumteul/domain/book/repository/BookLikeRepository.java
  src/main/java/com/kkumteul/domain/book/repository/BookRepository.java
  src/main/java/com/kkumteul/domain/book/repository/BookTopicRepository.java
  src/main/java/com/kkumteul/domain/book/service/BookService.java
  src/main/java/com/kkumteul/domain/book/service/impl/BookServiceImpl.java
  src/main/java/com/kkumteul/domain/mbti/entity/MBTI.java
  src/main/java/com/kkumteul/domain/personality/entity/Genre.java
  src/test/java/com/kkumteul/book/controller/BookControllerTest.java
  src/test/java/com/kkumteul/book/repository/BookRepositoryTest.java
  src/test/java/com/kkumteul/domain/book/controller/BookControllerTest.java
  src/test/java/com/kkumteul/domain/book/repository/BookLikeRepositoryTest.java
  src/test/java/com/kkumteul/domain/book/repository/BookRepositoryTest.java
  src/test/java/com/kkumteul/domain/book/service/BookServiceTest.java
Labels: ✨ Feat, 🎶 wontfix

#37 Refactor 프로필 이미지 multipart
  src/main/java/com/kkumteul/domain/user/controller/UserController.java
  src/main/java/com/kkumteul/domain/user/dto/UserResponseDto.java
  src/main/java/com/kkumteul/domain/user/dto/UserUpdateRequestDto.java
  src/main/java/com/kkumteul/domain/user/entity/User.java
  src/main/java/com/kkumteul/domain/user/service/UserService.java
  src/main/java/com/kkumteul/exception/handler/GlobalExceptionHandler.java
  src/test/java/com/kkumteul/domain/user/repository/UserRepositoryTest.java
Labels: 🚀 Refactor, 🎶 wontfix

#38 Feat 자녀 관리 API 구현
  src/main/java/com/kkumteul/domain/childprofile/controller/ChildProfileController.java
  src/main/java/com/kkumteul/domain/childprofile/dto/ChildProfileInsertRequestDto.java
  src/main/java/com/kkumteul/domain/childprofile/entity/ChildProfile.java
  src/main/java/com/kkumteul/domain/childprofile/service/ChildProfileService.java
  src/test/java/com/kkumteul/domain/childprofile/controller/ChildProfileControllerTest.java
  src/test/java/com/kkumteul/domain/childprofile/repository/ChildProfileRepositoryTest.java
  src/test/java/com/kkumteul/domain/childprofile/service/ChildProfileServiceTest.java
Labels: ✨ Feat, 🎶 wontfix

#27 Feat: 진단 히스토리 상세보기 API 구현
  src/main/java/com/kkumteul/domain/history/controller/ChildPersonalityHistoryController.java
  src/main/java/com/kkumteul/domain/history/dto/ChildPersonalityHistoryDetailDto.java
  src/main/java/com/kkumteul/domain/history/entity/ChildPersonalityHistory.java
  src/main/java/com/kkumteul/domain/history/repository/ChildPersonalityHistoryRepository.java
  src/main/java/com/kkumteul/domain/history/service/ChildPersonalityHistoryService.java
  src/test/java/com/kkumteul/domain/history/controller/ChildPersonalityHistoryControllerTest.java
  src/test/java/com/kkumteul/domain/history/repository/ChildPersonalityHistoryRepositoryTest.java
  src/test/java/com/kkumteul/domain/history/service/ChildPersonalityHistoryServiceTest.java
Labels: ✨ Feat

#40 Feat: 좋아요/싫어요 정보에 따른 성향 변경 구현
  build.gradle
  src/main/java/com/kkumteul/config/ChangePersonalityBatchConfig.java
  src/main/java/com/kkumteul/config/RedisConfig.java
  src/main/java/com/kkumteul/config/scheduler/ChangePersonalityScheduler.java
  src/main/java/com/kkumteul/domain/book/repository/BookRepository.java
  src/main/java/com/kkumteul/domain/book/service/BookLikeService.java
  src/main/java/com/kkumteul/domain/book/service/BookService.java
  src/main/java/com/kkumteul/domain/book/service/impl/BookServiceImpl.java
  src/main/java/com/kkumteul/domain/childprofile/entity/ChildProfile.java
  src/main/java/com/kkumteul/domain/childprofile/repository/ChildProfileRepository.java
  src/main/java/com/kkumteul/domain/childprofile/repository/GenreScoreRepository.java
  src/main/java/com/kkumteul/domain/childprofile/repository/TopicScoreRepository.java
  src/main/java/com/kkumteul/domain/childprofile/service/ChildProfileService.java
  src/main/java/com/kkumteul/domain/childprofile/service/PersonalityScoreService.java
  src/main/java/com/kkumteul/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/kkumteul/util/kafka/KafkaEventHandlingService.java
  src/main/java/com/kkumteul/util/kafka/KafkaTopic.java
  src/main/java/com/kkumteul/util/kafka/KafkaUtil.java
  src/main/java/com/kkumteul/util/redis/RedisKey.java
  src/main/java/com/kkumteul/util/redis/RedisUtil.java
  src/test/java/com/kkumteul/batch/ChangePersonalityBatchConfigTest.java
  src/test/java/com/kkumteul/batch/DeleteHistoryBatchConfigTest.java
  src/test/java/com/kkumteul/config/DeleteHistoryBatchTestConfig.java
  src/test/java/com/kkumteul/domain/survey/controller/SurveyControllerTest.java
  src/test/java/com/kkumteul/domain/survey/service/pattern/SurveyFacadeTest.java
Labels: ✨ Feat

#23 Feat: 관리자 페이지 API 구현
  src/main/java/com/kkumteul/domain/book/controller/AdminBookController.java
  src/main/java/com/kkumteul/domain/book/dto/AdminBookRequestDto.java
  src/main/java/com/kkumteul/domain/book/dto/AdminGetBookDetailResponseDto.java
  src/main/java/com/kkumteul/domain/book/dto/AdminGetBookListResponseDto.java
  src/main/java/com/kkumteul/domain/book/dto/BookDto.java
  src/main/java/com/kkumteul/domain/book/entity/Book.java
  src/main/java/com/kkumteul/domain/book/repository/BookMBTIRepository.java
  src/main/java/com/kkumteul/domain/book/repository/BookRepository.java
  src/main/java/com/kkumteul/domain/book/repository/BookTopicRepository.java
  src/main/java/com/kkumteul/domain/book/service/AdminBookService.java
  src/main/java/com/kkumteul/domain/book/service/BookMBTIService.java
  src/main/java/com/kkumteul/domain/book/service/BookTopicService.java
  src/main/java/com/kkumteul/domain/mbti/repository/MBTIRepository.java
  src/main/java/com/kkumteul/domain/mbti/service/MBTIService.java
  src/main/java/com/kkumteul/domain/personality/repository/GenreRepository.java
  src/main/java/com/kkumteul/domain/personality/repository/TopicRepository.java
  src/main/java/com/kkumteul/domain/personality/service/GenreService.java
  src/main/java/com/kkumteul/domain/personality/service/TopicService.java
  src/main/java/com/kkumteul/exception/BookNotFoundException.java
  src/main/java/com/kkumteul/exception/GlobalExceptionHandler.java
  src/main/resources/application-example.properties
  src/test/java/com/kkumteul/domain/adminbook/controller/AdminBookControllerTest.java
Labels: ✨ Feat, 🎶 wontfix

#25 Feat: 이벤트 API 구현
  src/main/java/com/kkumteul/domain/event/controller/EventController.java
  src/main/java/com/kkumteul/domain/event/dto/EventRequestDto.java
  src/main/java/com/kkumteul/domain/event/dto/EventResultResponseDto.java
  src/main/java/com/kkumteul/domain/event/entity/Event.java
  src/main/java/com/kkumteul/domain/event/repository/EventRepository.java
  src/main/java/com/kkumteul/domain/event/repository/JoinEventRepository.java
  src/main/java/com/kkumteul/domain/event/service/EventService.java
  src/main/java/com/kkumteul/domain/user/entity/User.java
  src/test/java/com/kkumteul/domain/event/service/EventServiceTest.java
Labels: ✨ Feat

#49 Refactor/#47 mypage edit
  src/main/java/com/kkumteul/domain/childprofile/dto/ChildProfileDetailDto.java
  src/main/java/com/kkumteul/domain/history/dto/ChildPersonalityHistoryDto.java
  src/main/java/com/kkumteul/domain/user/dto/UserResponseDto.java
  src/main/java/com/kkumteul/domain/user/service/UserService.java
Labels: ✨ Feat, 🎶 wontfix

#46 Feat: 도서에 mbti 성향 매핑 로직 구현
  src/main/java/com/kkumteul/config/HuggingConfig.java
  src/main/java/com/kkumteul/domain/HuggingFace/controller/HuggingFaceController.java
  src/main/java/com/kkumteul/domain/HuggingFace/dto/HuggingRequestDto.java
  src/main/java/com/kkumteul/domain/HuggingFace/exception/DuplicateBookException.java
  src/main/java/com/kkumteul/domain/HuggingFace/service/HuggingFaceService.java
  src/main/java/com/kkumteul/domain/book/entity/BookMBTI.java
  src/test/java/com/kkumteul/domain/book/repository/BookLikeRepositoryTest.java
  src/test/java/com/kkumteul/domain/book/repository/BookRepositoryTest.java
Labels: ✨ Feat, 🎶 wontfix

#50 Refactor: 좋아요/싫어요에 카프카 메시지 로직 추가, 성향 변경에 MBTI 반영
  src/main/java/com/kkumteul/config/ChangePersonalityBatchConfig.java
  src/main/java/com/kkumteul/domain/book/service/impl/BookServiceImpl.java
  src/main/java/com/kkumteul/domain/childprofile/entity/CumulativeMBTIScore.java
  src/main/java/com/kkumteul/domain/childprofile/service/PersonalityScoreService.java
Labels: 🚀 Refactor

#26 Feat: 추천 로직 구현
  build.gradle
  src/main/java/com/kkumteul/KkumteulApplication.java
  src/main/java/com/kkumteul/config/BatchConfig.java
  src/main/java/com/kkumteul/config/RedisConfig.java
  src/main/java/com/kkumteul/domain/book/entity/Book.java
  src/main/java/com/kkumteul/domain/book/repository/BookLikeRepository.java
  src/main/java/com/kkumteul/domain/book/repository/BookRepository.java
  src/main/java/com/kkumteul/domain/childprofile/entity/ChildProfile.java
  src/main/java/com/kkumteul/domain/childprofile/repository/ChildProfileRepository.java
  src/main/java/com/kkumteul/domain/history/entity/ChildPersonalityHistory.java
  src/main/java/com/kkumteul/domain/history/repository/ChildPersonalityHistoryRepository.java
  src/main/java/com/kkumteul/domain/recommendation/controller/RecommendationController.java
  src/main/java/com/kkumteul/domain/recommendation/dto/BookDataDto.java
  src/main/java/com/kkumteul/domain/recommendation/dto/ChildDataDto.java
  src/main/java/com/kkumteul/domain/recommendation/dto/GenreDto.java
  src/main/java/com/kkumteul/domain/recommendation/dto/RecommendBookDto.java
  src/main/java/com/kkumteul/domain/recommendation/dto/RecommendationResultDto.java
  src/main/java/com/kkumteul/domain/recommendation/dto/TopicDto.java
  src/main/java/com/kkumteul/domain/recommendation/filter/CollaborativeFilter.java
  src/main/java/com/kkumteul/domain/recommendation/filter/ContentBasedFilter.java
  src/main/java/com/kkumteul/domain/recommendation/filter/SimilarityCalculator.java
  src/main/java/com/kkumteul/domain/recommendation/repository/RecommendationRepository.java
  src/main/java/com/kkumteul/domain/recommendation/service/BatchScheduler.java
  src/main/java/com/kkumteul/domain/recommendation/service/RecommendationService.java
  src/test/java/com/kkumteul/recommendation/controller/RecommendationControllerTest.java
  src/test/java/com/kkumteul/recommendation/service/RecommendationServiceTest.java
Labels: ✨ Feat

#53 Feat: 자녀 프로필 검증 API 구현
  src/main/java/com/kkumteul/domain/user/controller/UserController.java
  src/main/java/com/kkumteul/domain/user/service/UserService.java
Labels: ✨ Feat

#55 Refactor: API 매핑 시 발생했던 문제 해결
  src/main/java/com/kkumteul/config/ChangePersonalityBatchConfig.java
  src/main/java/com/kkumteul/domain/history/controller/ChildPersonalityHistoryController.java
  src/main/java/com/kkumteul/domain/history/dto/ChildPersonalityHistoryDetailDto.java
  src/main/java/com/kkumteul/domain/history/entity/MBTIScore.java
  src/main/java/com/kkumteul/domain/history/service/ChildPersonalityHistoryService.java
  src/main/java/com/kkumteul/domain/mbti/dto/MBTIPercentageDto.java
  src/main/java/com/kkumteul/domain/mbti/service/MBTIService.java
  src/main/java/com/kkumteul/domain/survey/dto/SurveyResultDto.java
  src/main/java/com/kkumteul/domain/survey/service/pattern/SurveyFacadeImpl.java
Labels: 🚀 Refactor, 🛠️ Fix

#59 Fix: 테스트용 DB 사용을 위해 ActiveProfiles 어노테이션 추가
  src/test/java/com/kkumteul/domain/adminbook/controller/AdminBookControllerTest.java
Labels: 🐛 Bug, 🎶 wontfix

#35 feat: Spring Security 및 관리자 계정 설정
  build.gradle
  src/main/java/PasswordEncoderUtil.java
  src/main/java/com/kkumteul/DataInitializer.java
  src/main/java/com/kkumteul/KkumteulApplication.java
  src/main/java/com/kkumteul/config/AdminUserConfig.java
  src/main/java/com/kkumteul/config/SecurityConfig.java
  src/main/java/com/kkumteul/controller/AdminController.java
  src/main/java/com/kkumteul/controller/AuthController.java
  src/main/java/com/kkumteul/controller/ProfileController.java
  src/main/java/com/kkumteul/controller/UserController.java
  src/main/java/com/kkumteul/domain/user/entity/Role.java
  src/main/java/com/kkumteul/domain/user/entity/User.java
  src/main/java/com/kkumteul/domain/user/repository/UserRepository.java
  src/main/java/com/kkumteul/dto/AuthenticationRequest.java
  src/main/java/com/kkumteul/dto/AuthenticationResponse.java
  src/main/java/com/kkumteul/exception/GlobalExceptionHandler.java
  src/main/java/com/kkumteul/security/CustomUserDetailsService.java
  src/main/java/com/kkumteul/security/JwtAuthenticationFilter.java
  src/main/java/com/kkumteul/security/JwtTokenProvider.java
  src/main/java/com/kkumteul/service/UserService.java
Labels: ✨ Feat, 🛠️ Fix

#64 fix : 토큰 관련 Redis 방식으로 수정
  src/main/java/com/kkumteul/config/RedisConfig.java
  src/main/java/com/kkumteul/controller/AuthController.java
  src/main/java/com/kkumteul/controller/ProfileController.java
  src/main/java/com/kkumteul/service/UserService.java
Labels: ✨ Feat, 🛠️ Fix

#62 Feat: 추천 버그 수정
  src/main/java/com/kkumteul/KkumteulApplication.java
  src/main/java/com/kkumteul/config/AsyncConfig.java
  src/main/java/com/kkumteul/config/RecommendationBatchConfig.java
  src/main/java/com/kkumteul/config/scheduler/RecommendationBatchScheduler.java
  src/main/java/com/kkumteul/domain/recommendation/controller/RecommendationController.java
  src/main/java/com/kkumteul/domain/recommendation/service/AsyncService.java
  src/main/java/com/kkumteul/domain/recommendation/service/RecommendationService.java
  src/main/java/com/kkumteul/domain/recommendation/service/TransactionalService.java
  src/test/java/com/kkumteul/recommendation/service/RecommendAsyncTest.java
Labels: 🎶 wontfix, 🛠️ Fix

#61 Feat: 빈 DB로 테스트 코드 실행
  src/test/java/com/kkumteul/domain/book/controller/BookControllerTest.java
  src/test/java/com/kkumteul/domain/book/repository/BookLikeRepositoryTest.java
  src/test/java/com/kkumteul/domain/book/repository/BookRepositoryTest.java
  src/test/java/com/kkumteul/domain/book/service/BookServiceTest.java
Labels: 🎶 wontfix, 🛠️ Fix

#69 Fix: 메인페이지 현재 진행중인 이벤트 조회 API 구현
  src/main/java/com/kkumteul/domain/event/controller/EventController.java
  src/main/java/com/kkumteul/domain/event/dto/EventDto.java
  src/main/java/com/kkumteul/domain/event/repository/EventRepository.java
  src/main/java/com/kkumteul/domain/event/service/EventService.java
  src/main/java/com/kkumteul/filter/LoginFilter.java
Labels: ✨ Feat, 🛠️ Fix

#72 Feat: 로그인 되어있지 않을 시 기본 추천
  build.gradle
  src/main/java/com/kkumteul/config/SecurityConfig.java
  src/main/java/com/kkumteul/domain/history/service/ChildPersonalityHistoryService.java
  src/main/java/com/kkumteul/domain/recommendation/controller/RecommendationController.java
  src/main/java/com/kkumteul/domain/recommendation/service/RecommendationService.java
  src/main/java/com/kkumteul/domain/survey/controller/SurveyController.java
  src/main/java/com/kkumteul/domain/survey/dto/SurveyResultRequestDto.java
  src/main/java/com/kkumteul/domain/survey/service/pattern/SurveyFacade.java
  src/main/java/com/kkumteul/domain/survey/service/pattern/SurveyFacadeImpl.java
  src/test/java/com/kkumteul/domain/survey/controller/SurveyControllerTest.java
Labels: ✨ Feat

#73 Refactor: userId JWT 방식으로 변경
  src/main/java/com/kkumteul/domain/event/controller/EventController.java
Labels: 🚀 Refactor

#76 Refactor: 리액트에서 에러 메시지 반환
  src/main/java/com/kkumteul/domain/book/dto/GetBookDetailResponseDto.java
  src/main/java/com/kkumteul/exception/handler/GlobalExceptionHandler.java
Labels: 🚀 Refactor, 🎶 wontfix

#80 Refactor: refactor event logic
  build.gradle
  src/main/java/com/kkumteul/config/RedisConfig.java
  src/main/java/com/kkumteul/domain/event/service/EventService.java
Labels: 🚀 Refactor

#81 Feat: 좋아요 상태 조회 추가
  src/main/java/com/kkumteul/domain/book/controller/BookController.java
  src/main/java/com/kkumteul/domain/book/dto/GetLikeStatusResponse.java
  src/main/java/com/kkumteul/domain/book/repository/BookLikeRepository.java
  src/main/java/com/kkumteul/domain/book/service/BookService.java
  src/main/java/com/kkumteul/domain/book/service/impl/BookServiceImpl.java
Labels: 🚀 Refactor

#84 Fix: 도서 좋아요/싫어요 상태 변화 버그 수정
  src/main/java/com/kkumteul/domain/book/controller/BookController.java
  src/main/java/com/kkumteul/domain/book/dto/GetLikeStatusResponse.java
  src/main/java/com/kkumteul/domain/book/repository/BookLikeRepository.java
  src/main/java/com/kkumteul/domain/book/service/BookService.java
  src/main/java/com/kkumteul/domain/book/service/impl/BookServiceImpl.java
Labels: 🎶 wontfix, 🛠️ Fix
