Repository KKUMTEUL/KKUMTEUL-backend, pull requests merged in 2024-11, with the labels that each got.

#86 Fix: 기본 추천 로직 성능 개선
  src/main/java/com/kkumteul/domain/book/repository/BookRepository.java
Labels: 🛠️ Fix

#87 Refactor: 마이페이지 리팩토링 작업
  src/main/java/com/kkumteul/domain/childprofile/dto/ChildProfileDto.java
  src/main/java/com/kkumteul/domain/childprofile/dto/ChildProfileInsertRequestDto.java
  src/main/java/com/kkumteul/domain/childprofile/service/ChildProfileService.java
  src/main/java/com/kkumteul/domain/user/entity/User.java
  src/main/java/com/kkumteul/domain/user/service/UserService.java
Labels: 🚀 Refactor, 🎶 wontfix

#88 Test: jwt 이후 테스트 코드 수정
  build.gradle
  src/test/java/com/kkumteul/domain/book/controller/BookControllerTest.java
  src/test/java/com/kkumteul/domain/book/repository/BookLikeRepositoryTest.java
  src/test/java/com/kkumteul/domain/book/repository/BookRepositoryTest.java
  src/test/java/com/kkumteul/domain/book/service/BookServiceTest.java
Labels: 🎶 wontfix, 📰 Test

#90 Fix/#85 recommend
  src/main/java/com/kkumteul/domain/recommendation/service/RecommendationService.java
Labels: 🛠️ Fix

#92 Fix: Security 도입으로 인한 테스트 실패 부분 수정
  src/main/java/com/kkumteul/config/SecurityConfig.java
  src/test/java/com/kkumteul/batch/ChangePersonalityBatchConfigTest.java
  src/test/java/com/kkumteul/domain/childprofile/controller/ChildProfileControllerTest.java
  src/test/java/com/kkumteul/domain/code/controller/CommonCodeControllerTest.java
  src/test/java/com/kkumteul/domain/history/controller/ChildPersonalityHistoryControllerTest.java
  src/test/java/com/kkumteul/domain/history/service/ChildPersonalityHistoryServiceTest.java
  src/test/java/com/kkumteul/domain/recommendation/controller/RecommendationControllerTest.java
  src/test/java/com/kkumteul/domain/survey/controller/SurveyControllerTest.java
Labels: 🎶 wontfix, 🛠️ Fix, 📰 Test

#94 Fix: 유저 정보 반환값 수정
  src/main/java/com/kkumteul/domain/user/dto/UserResponseDto.java
Labels: 🎶 wontfix, 🛠️ Fix

#95 Fix: 테스트 코드 수정 및 추천 로직 중복 수정
  src/main/java/com/kkumteul/domain/recommendation/service/RecommendationService.java
  src/test/java/com/kkumteul/domain/recommendation/service/RecommendAsyncTest.java
  src/test/java/com/kkumteul/domain/recommendation/service/RecommendationCacheTest.java
  src/test/java/com/kkumteul/domain/recommendation/service/RecommendationServiceTest.java
  src/test/java/com/kkumteul/recommendation/controller/RecommendationControllerTest.java
  src/test/java/com/kkumteul/recommendation/service/RecommendationServiceTest.java
Labels: 🛠️ Fix, 📰 Test

#96 Refactor: 이벤트 로직 수정 및 개선
  build.gradle
  src/main/java/com/kkumteul/config/RedisConfig.java
  src/main/java/com/kkumteul/config/SecurityConfig.java
  src/main/java/com/kkumteul/domain/event/controller/EventController.java
  src/main/java/com/kkumteul/domain/event/dto/JoinEventRequestDto.java
  src/main/java/com/kkumteul/domain/event/service/EventService.java
  src/main/java/com/kkumteul/domain/event/service/JoinEventService.java
  src/main/java/com/kkumteul/domain/event/service/TicketInitializationService.java
  src/main/java/com/kkumteul/domain/event/service/TicketService.java
  src/main/java/com/kkumteul/util/redis/RedisMessageSubscriber.java
Labels: 🚀 Refactor

#97 Feat: 이벤트 당첨 결과 반환 API 구현
  src/main/java/com/kkumteul/domain/event/controller/EventController.java
  src/main/java/com/kkumteul/domain/event/dto/EventResultResponseDto.java
  src/main/java/com/kkumteul/domain/event/repository/JoinEventRepository.java
  src/main/java/com/kkumteul/domain/event/service/JoinEventService.java
Labels: ✨ Feat

#99 fix: 도서 검색 쿼리문 피드백 반영
  src/main/java/com/kkumteul/domain/book/repository/BookRepository.java
Labels: 🎶 wontfix, 🛠️ Fix

#100 Fix : 필터링 기능 보완
  src/main/java/com/kkumteul/domain/book/controller/AdminBookController.java
  src/main/java/com/kkumteul/domain/book/dto/AdminBookFilterResponseDto.java
  src/main/java/com/kkumteul/domain/book/repository/BookRepository.java
  src/main/java/com/kkumteul/domain/book/service/AdminBookService.java
  src/main/java/com/kkumteul/domain/mbti/repository/MBTIRepository.java
  src/main/java/com/kkumteul/domain/mbti/service/MBTIService.java
Labels: ✨ Feat, 🎶 wontfix

#101 Test: 시큐리티 도입 후 도서관리테스트 수정
  src/test/java/com/kkumteul/domain/adminbook/controller/AdminBookControllerTest.java
Labels: 🎶 wontfix, 📰 Test

#102 Feat: 이벤트 API 구현
  src/main/java/com/kkumteul/domain/event/controller/AdminEventController.java
  src/main/java/com/kkumteul/domain/event/entity/Event.java
  src/main/java/com/kkumteul/domain/event/repository/EventRepository.java
  src/main/java/com/kkumteul/domain/event/service/AdminEventService.java
  src/main/java/com/kkumteul/exception/AdminEventNotFoundException.java
Labels: ✨ Feat, 🎶 wontfix
